# Generated by Django 5.0.6 on 2024-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmcq',
            name='correct_options',
        ),
        migrations.AddField(
            model_name='mmcq',
            name='is_O1_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mmcq',
            name='is_O2_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mmcq',
            name='is_O3_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mmcq',
            name='is_O4_correct',
            field=models.BooleanField(default=False),
        ),
    ]
