# Generated by Django 5.0.6 on 2024-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ImageField(null=True, upload_to='questions/questions/'),
        ),
    ]
