# Generated by Django 5.0.6 on 2024-06-09 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^(CH)|(MA)|(PH)\\d{5}$', 'ID must be of format: Subject Letter + 2 digits')]),
        ),
    ]
