# Generated by Django 5.0.6 on 2024-05-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_mmcq_correct_options_mmcq_is_o1_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_questions', to='questions.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='questions.chapter'),
        ),
    ]
