# Generated by Django 5.0.6 on 2024-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SMCQ', 'Single Option Correct'), ('MMCQ', 'Multiple Option Correct'), ('INT', 'Integer Answer Type'), ('SUBJ', 'Subjective'), ('MATCH', 'Match the Matrix')], max_length=128),
        ),
    ]
