# Generated by Django 5.0.6 on 2024-06-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answerintegertype_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerintegertype',
            name='correct_answer',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='AnswerSubjective',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('explanation', models.ImageField(null=True, upload_to='explanations/')),
                ('correct_answer', models.CharField(max_length=512, null=True)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='answer_smcq', to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
