# Generated by Django 5.0.6 on 2024-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_solved_questions_topic_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
