# Generated by Django 5.0.6 on 2024-06-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answerintegertype_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerintegertype',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='question_answer', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answermmcq',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='question_answer', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answersmcq',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='question_answer', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answersubjective',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='question_answer', to='questions.question'),
        ),
    ]
