# Generated by Django 5.0.6 on 2024-06-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DppPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mlAssist/dpp-final/')),
            ],
        ),
        migrations.CreateModel(
            name='PaperPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mlAssist/paper/')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mlAssist/results/')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlAssist.paperpdf')),
            ],
        ),
    ]
