# Generated by Django 5.0.6 on 2024-06-12 07:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^(CH)|(MA)|(PH)\\d{2}$', 'ID must be of format: Subject Letter + 2 digits')])),
                ('name', models.CharField(max_length=128)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mockTest.test')),
                ('start_time', models.DateTimeField()),
            ],
            bases=('mockTest.test',),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submission_time', models.DateTimeField(null=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='mockTest.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
