# Generated by Django 5.0.6 on 2024-06-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testquestionattempt',
            old_name='test_attempt_id',
            new_name='test_attempt',
        ),
        migrations.RenameField(
            model_name='testquestionattempt',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='testquestionattempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testquestionattempt',
            name='test_question_id',
        ),
        migrations.AddField(
            model_name='livetest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testquestionattempt',
            name='test_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockTest.testquestion'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testquestionattempt',
            name='time_taken',
            field=models.BooleanField(null=True),
        ),
    ]
