# Generated by Django 5.0.6 on 2024-09-17 13:32

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0001_initial'),
        ('questions', '0006_alter_answerintegertype_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Unattempted', 'Unattempted'), ('Attempted', 'Attempted'), ('Marked', 'Marked for Review'), ('Skipped', 'not visited')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mockTest.test'),
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.icon')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='mockTest.testseries'),
        ),
    ]
