# Generated by Django 5.0.6 on 2024-06-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='creator',
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Unattempted', 'Unattempted'), ('Skipped', 'not visited'), ('Attempted', 'Attempted')], max_length=64, null=True),
        ),
    ]
