# Generated by Django 5.0.6 on 2024-06-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.CharField(default='hello $ instructions', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_attempted', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockTest.test')),
            ],
        ),
    ]
