# Generated by Django 5.0.6 on 2024-09-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0002_alter_testquestionattempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='mockTest.testseries'),
        ),
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Marked', 'Marked for Review'), ('Skipped', 'not visited'), ('Unattempted', 'Unattempted'), ('Attempted', 'Attempted')], max_length=64, null=True),
        ),
    ]
