# Generated by Django 5.0.6 on 2024-06-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0002_remove_test_creator_alter_test_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Attempted', 'Attempted'), ('Unattempted', 'Unattempted'), ('Skipped', 'not visited')], max_length=64, null=True),
        ),
    ]
