# Generated by Django 5.0.6 on 2024-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0002_rename_test_id_testattempt_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='instructions',
            field=models.TextField(default='1. The Test consists of Three Sections:- Physics, Chemistry, Mathematics.\n\n2. Total number of Questions:- 54 (Each section consists of 18 questions).\n\n3 .Each Section consists of Three Sub-Section :- Section A , Section B , Section C\n\n4. Marking Scheme -\nFor Section A\nInteger Type Questions (Single Digit Integer) (8 Questions)\nFor each Question, enter the correct single digit integer value.\nPositive Marks : +3 , Negative Marks : 00\n\nFor Section B\nOne or More than one correct (6 Questions)\nFor each Question, choose the option(s) corresponding to (all) the correct answers.\nPositive Marks : +4 , Negative Marks : -1\n\nFor Section C\nSingle Correct (4 Questions)\nFor each Question, choose the correct option corresponding to the correct Answer.\nEach Question has Four options (1),(2),(3),(4). Only ONE of these options is the correct answer.\nPositive Marks : +4 , Negative Marks : -1\n\n5. Test Duration:- 180 mins.\n\n6. Test Timing:- 14:00 PM.', max_length=1024, null=True),
        ),
    ]
