# Generated by Django 5.0.6 on 2024-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0003_alter_test_series_alter_testquestionattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Skipped', 'not visited'), ('SaveMarked', 'Saved and Marked for Review'), ('Unattempted', 'Unattempted'), ('Marked', 'Marked for Review'), ('Attempted', 'Attempted')], max_length=64, null=True),
        ),
    ]
