# Generated by Django 5.0.6 on 2024-06-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0003_remove_test_instructions_alter_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Attempted', 'Attempted'), ('Skipped', 'not visited'), ('Unattempted', 'Unattempted')], max_length=64, null=True),
        ),
    ]
