# Generated by Django 5.0.6 on 2024-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockTest', '0004_test_image_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image_test',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testquestionattempt',
            name='status',
            field=models.CharField(choices=[('Skipped', 'Skipped'), ('Attempted', 'Attempted'), ('Unattempted', 'Unattempted')], max_length=64, null=True),
        ),
    ]
