# Generated by Django 5.0.6 on 2024-06-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_question', models.IntegerField()),
                ('solved_question', models.IntegerField()),
                ('chapter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.chapter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_status', models.BooleanField(default=False)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
