# Generated by Django 5.0.6 on 2024-06-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answerintegertype_question_id_and_more'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionAttempt',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_attempted', models.BooleanField()),
                ('is_correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
