# Generated by Django 5.0.6 on 2024-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='solved_question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='adv_solved_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='adv_total_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='main_solved_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='main_total_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module_solved_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module_total_question',
            field=models.IntegerField(default=0),
        ),
    ]
