# Generated by Django 5.0.6 on 2024-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_solved_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='adv_total_question',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='main_total_question',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module_total_question',
            field=models.IntegerField(),
        ),
    ]
