# Generated by Django 5.0.6 on 2024-06-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_adv_total_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='adv_solved_question',
            new_name='adv_solved_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='adv_total_question',
            new_name='adv_total_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='main_solved_question',
            new_name='main_solved_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='main_total_question',
            new_name='main_total_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='module_solved_question',
            new_name='module_solved_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='module_total_question',
            new_name='module_total_questions',
        ),
    ]
