# Generated by Django 5.0.6 on 2024-06-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answerintegertype_question_id_and_more'),
        ('quiz', '0005_rename_adv_solved_question_quiz_adv_solved_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='solved_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QuizQuestionAttemptInt',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('marked_answer', models.FloatField()),
                ('quiz_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionAttemptMmcq',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('is_O1_marked', models.BooleanField()),
                ('is_O2_marked', models.BooleanField()),
                ('is_O3_marked', models.BooleanField()),
                ('is_O4_marked', models.BooleanField()),
                ('quiz_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionAttemptSmcq',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('marked_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('quiz_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuizQuestionAttempt',
        ),
    ]
