# Generated by Django 5.0.6 on 2024-06-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answerintegertype_question_id_and_more'),
        ('quiz', '0006_alter_quizquestion_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionattemptint',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answerintegertype'),
        ),
        migrations.AddField(
            model_name='quizquestionattemptmmcq',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answermmcq'),
        ),
        migrations.AddField(
            model_name='quizquestionattemptsmcq',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answersmcq'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='solved_status',
            field=models.BooleanField(default=False),
        ),
    ]
