# Generated by Django 5.0.6 on 2024-07-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15, null=True, verbose_name='MobileNumber')),
                ('mentor_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=12)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='mentor_pfp/')),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('IIT', models.CharField(max_length=48)),
                ('branch', models.CharField(max_length=48, null=True)),
                ('state', models.CharField(max_length=48)),
                ('dropper_status', models.CharField(choices=[('Dropper', 'Dropper'), ('Non-dropper', 'Non-dropper')], max_length=28)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=28)),
                ('did_you_change', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=28)),
                ('physics_rank', models.IntegerField()),
                ('chemistry_rank', models.IntegerField()),
                ('maths_rank', models.IntegerField()),
                ('bandwidth', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=12)),
                ('state', models.CharField(max_length=48)),
                ('dropper_status', models.CharField(choices=[('Dropper', 'Dropper'), ('Non-dropper', 'Non-dropper')], max_length=28)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=28)),
                ('did_you_change', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=28)),
                ('physics_rank', models.IntegerField()),
                ('chemistry_rank', models.IntegerField()),
                ('maths_rank', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorMenteeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloted_mentor_compatibility', models.FloatField()),
                ('extra_mentor_1_compatibility', models.FloatField()),
                ('extra_mentor_2_compatibility', models.FloatField()),
                ('extra_mentor_3_compatibility', models.FloatField()),
                ('alloted_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='mentorship.mentor')),
                ('extra_mentor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_1', to='mentorship.mentor')),
                ('extra_mentor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_2', to='mentorship.mentor')),
                ('extra_mentor_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_3', to='mentorship.mentor')),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='mentorship.mentee')),
            ],
        ),
    ]
