# Generated by Django 5.0.6 on 2024-06-25 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mentor_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=12)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='mentor_pfp/')),
                ('about', models.TextField(blank=True, max_length=512, null=True)),
                ('IIT', models.CharField(max_length=48)),
                ('state', models.CharField(max_length=48)),
                ('dropper_status', models.CharField(choices=[('Dropper', 'Dropper'), ('Non-dropper', 'Non-dropper')], max_length=28)),
                ('medium', models.CharField(choices=[('english', 'english'), ('hindi', 'hindi')], max_length=28)),
                ('did_you_change', models.BooleanField()),
                ('physics_rank', models.IntegerField()),
                ('chemistry_rank', models.IntegerField()),
                ('maths_rank', models.IntegerField()),
            ],
        ),
    ]
