# Generated by Django 5.0.6 on 2024-06-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='did_you_change',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=28),
        ),
    ]
