# Generated by Django 5.0.6 on 2024-06-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentor_did_you_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=28),
        ),
    ]
