# Generated by Django 5.0.6 on 2024-06-26 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MentorMenteeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField()),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentee', verbose_name='relationship')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentor', verbose_name='relationship')),
            ],
        ),
    ]
