# Generated by Django 5.0.6 on 2024-06-26 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_mentor_bandwidth_mentor_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='mentorship.mentee'),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='mentorship.mentor'),
        ),
    ]
