# Generated by Django 5.0.6 on 2024-06-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_alter_mentormenteerelationship_mentee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentormenteerelationship',
            old_name='compatibility_score',
            new_name='alloted_compatibility',
        ),
        migrations.RenameField(
            model_name='mentormenteerelationship',
            old_name='mentor',
            new_name='alloted_mentor',
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_1', to='mentorship.mentor'),
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_1_compatibility',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_2', to='mentorship.mentor'),
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_2_compatibility',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_3', to='mentorship.mentor'),
        ),
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='extra_mentor_3_compatibility',
            field=models.FloatField(null=True),
        ),
    ]
