# Generated by Django 5.0.6 on 2024-06-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0008_rename_compatibility_score_mentormenteerelationship_alloted_compatibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_1', to='mentorship.mentor'),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_1_compatibility',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_2', to='mentorship.mentor'),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_2_compatibility',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_3', to='mentorship.mentor'),
        ),
        migrations.AlterField(
            model_name='mentormenteerelationship',
            name='extra_mentor_3_compatibility',
            field=models.FloatField(),
        ),
    ]
