# Generated by Django 5.0.6 on 2024-06-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0009_alter_mentormenteerelationship_extra_mentor_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentormenteerelationship',
            old_name='alloted_compatibility',
            new_name='alloted_mentor_compatibility',
        ),
    ]
