# Generated by Django 5.0.6 on 2024-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0014_alter_mentor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='branch',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True, verbose_name='MobileNumber'),
        ),
    ]
