# Generated by Django 5.0.6 on 2024-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0015_mentor_branch_mentor_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
