# Generated by Django 5.0.6 on 2024-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='temp_user_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
