# Generated by Django 5.0.6 on 2024-06-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_admin', 'Can check if user is admin'), ('is_payment_done', 'Can check if payment is done'), ('is_mentor_alloted', 'Can check if mentor is allotted'))},
        ),
    ]
