# Generated by Django 5.0.6 on 2024-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermobilenootp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobilenootp',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usermobilenootp',
            name='user_identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
