# Generated by Django 5.0.6 on 2024-07-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usermobilenootp_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_admin', 'Can check if user is admin'), ('is_mobile_no_verified', 'Can check if mobile number is verified'), ('is_payment_done', 'Can check if payment is done'), ('is_mentor_alloted', 'Can check if mentor is allotted'))},
        ),
        migrations.AddField(
            model_name='user',
            name='is_mobile_no_verified',
            field=models.BooleanField(default=False),
        ),
    ]
