# Generated by Django 5.0.6 on 2024-06-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_alter_answerintegertype_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='notes/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.chapter')),
            ],
        ),
    ]
