# Generated by Django 5.0.6 on 2024-06-26 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='notes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
