# Generated by Django 5.0.6 on 2024-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
